### ISSUE TITLE
A problem with the socks processor being terminated.

### ISSUE THREAD

**Issue by odkrys** [3proxy/3proxy#869]
Hi.
I am using only the socks binary in 3proxy.

Socks is used as a relay server and binded to vpn interface.

socks -i192.168.1.1 -p1080 -Dewg0 -d -t -s0

An old compilation of socks works fine, but a recent compilation of socks has problems.

It just shuts down the processor.

This is the gdb result. I'm not an engineer, so I don't know what's causing the problem.
```
[New LWP 19697]
[New LWP 19698]
[New LWP 19699]
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 152 "socks" received signal SIGPIPE, Broken pipe.
[Switching to LWP 19692]
__cp_end () at src/thread/x86_64/syscall_cp.s:29
29      src/thread/x86_64/syscall_cp.s: No such file or directory.
(gdb) bt
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fdc6be in __syscall_cp_c (nr=44, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=28) at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fc7b89 in sendto (fd=<optimized out>, buf=<optimized out>, len=<optimized out>, flags=<optimized out>, addr=<optimized out>, alen=<optimized out>) at src/network/sendto.c:6
#3  0x0000000000403f10 in sockmap (param=param@entry=0x84a2e0, timeo=<optimized out>, usesplice=<optimized out>, usesplice@entry=0) at sockmap.c:262
#4  0x0000000000407192 in sockschild (param=0x84a2e0) at socks.c:350
#5  0x0000000000406173 in threadfunc (p=0x84a2e0) at proxymain.c:77
#6  0x00007ffff7fdd15e in start (p=0x7ffff7de2ae8) at src/thread/pthread_create.c:195
#7  0x00007ffff7fdf2e2 in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

(gdb) up
#1  0x00007ffff7fdc6be in __syscall_cp_c (nr=44, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=28) at src/thread/pthread_cancel.c:33
33      src/thread/pthread_cancel.c: No such file or directory.

(gdb) up
#2  0x00007ffff7fc7b89 in sendto (fd=<optimized out>, buf=<optimized out>, len=<optimized out>, flags=<optimized out>, addr=<optimized out>, alen=<optimized out>) at src/network/sendto.c:6
6       src/network/sendto.c: No such file or directory.

(gdb) up
#3  0x0000000000403f10 in sockmap (param=param@entry=0x84a2e0, timeo=<optimized out>, usesplice=<optimized out>, usesplice@entry=0) at sockmap.c:262
262                     res = so._sendto(param->clisock, (char *)param->srvbuf + param->srvoffset, (int)MIN(inserverbuf,fromserver), 0, (struct sockaddr*)&param->sincr, sasize);

(gdb) l
257                     if(!inserverbuf){
258                             param->srvinbuf = param->srvoffset = 0;
259                             continue;
260                     }
261                     sasize = sizeof(param->sincr);
262                     res = so._sendto(param->clisock, (char *)param->srvbuf + param->srvoffset, (int)MIN(inserverbuf,fromserver), 0, (struct sockaddr*)&param->sincr, sasize);
263                     if(res <= 0) {
264                             TOCLIENT = 0;
265                             if(errno && errno != EAGAIN && errno != EINTR){
266                                     CLIENTTERM = 1;

(gdb) up
#4  0x0000000000407192 in sockschild (param=0x84a2e0) at socks.c:350
350                                     param->res = mapsocket(param, conf.timeouts[CONNECTION_S]);

(gdb) l
345                                             memcpy (buf+2, SAPORT(&param->sinsr), 2);
346                                             memcpy (buf+4, SAADDR(&param->sinsr), 4);
347                                             socksend(param->clisock, buf, 8, conf.timeouts[STRING_S]);
348                                     }
349
350                                     param->res = mapsocket(param, conf.timeouts[CONNECTION_S]);
351                                     break;
352                             case 3:
353                                     param->sinsr = param->req;
354                                     myfree(buf);

(gdb) up
#5  0x0000000000406173 in threadfunc (p=0x84a2e0) at proxymain.c:77
77              ((struct clientparam *) p)->srv->pf((struct clientparam *)p);

(gdb) l
72              sigfillset(&mask);
73              if(param->srv->service != S_UDPPM)pthread_sigmask(SIG_SETMASK, &mask, NULL);
74      #endif
75      #endif
76
77              ((struct clientparam *) p)->srv->pf((struct clientparam *)p);
78       }
79      #ifdef _WIN32
80       return 0;
81      #else

```

**Comment by odkrys** [comment]
It seems I caught the wrong breakpoint.
The problem was here 
```
error = so._poll(&srv.fds, 1, 1000);
```
and after changing the file limit settings the problem seemed to be resolved.
